openapi: 3.0.1
info:
  title: Vas-Ai
  description: |-
    API del modulo Vas-Ai
    <br>Timestamp generazione: 2020-02-16T17:11:52.00
  version: 2.3.0
paths:
  /vas-ai/nlp/stemming:
    post:
      tags:
      - Lemming
      summary: Restituisce la frase fornita in ingresso stemmata
      description: Restituisce la frase fornita in ingresso stemmata
      operationId: Stemming
      parameters:
      - name: sentence
        in: query
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        200:
          description: Frase stemmata correttamente
          content:
            application/json:
              schema:
                type: string
                items:
                  $ref: 'VAS-Response/content'
   
  /vas-ai/nlp/lemming:
    post:
      tags:
      - Stemming
      summary: Genera il lemma della frase in ingresso e lo fornisce in output
      description: Genera il lemma della frase in ingresso e lo fornisce in output.
      operationId: Lemming
      parameters:
      - name: sentence
        in: query
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        200:
          description: Il lemma della frase fornita
          content:
            application/json:
              schema:
                $ref: 'VAS-Response/content'
                
                
  /vas-ai/nlp/landetect:
    post:
      tags:
      - LanguageDetection
      summary: Identifica la lingua utilizzata analizzando la frase in ingresso.
      description: Identifica la lingua utilizzata analizzando la frase in ingresso.
      operationId: landetect
      parameters:
      - name: sentence
        in: query
        schema:
          type: string
      responses:
        200:
          description: Le due lettere identificanti la lingua utilizzata
          content:
            application/json:
              schema:
                $ref: ''

       
  /vas-ai/nlp/generateLink:
    post:
      tags:
      -  Link generation
      summary: Consente la generazione automatica di link sulla base del sito e delle keyword inserite.
      description: Consente la generazione automatica di link sulla base del sito e delle keyword inserite.
      operationId: generateLink
      parameters:
      - name: siteName
        in: query
        required: true
        schema:
          type: string
      - name: researchKey
        in: query
        required: true
        schema:
          type: string
      responses:
        200:
          description: Gli n link corrispondenti ai parametri di ricerca
          content:
            application/json:
              schema:
                $ref: ''
        
        
  /vas-ai/nlp/findTemplate:
    post:
      tags:
      -  Identificazione template specifico
      summary: Cerca il template specifico tale da soddisfare le richieste dell'utente basandosi sulla frase inserita in input.
      description: Cerca il template specifico tale da soddisfare le richieste dell'utente basandosi sulla frase fornita in input.
      operationId: findTemplate
      parameters:
      - name: sentence
        in: path
        required: true
        schema:
          type: string
      responses:
        200:
          description: La lista degli id tali da soddisfare la richiesta dell'utente
          content:
            application/json:
              schema:
                $ref: 'VAS-Response/content'
        
        
  /vas-ai/nlp/findNextQuestionExp:
    post:
      tags:
      - Identificazione domanda successiva
      summary: Cerca l'id della domanda successiva, basandosi sulla frase inserita dall'utente
      description: cerca l'id della domanda successiva, basandosi sulla frase inserita dall'utente.
      operationId: findNextQuestionExp
      parameters:
      - name: sentence
        in: query
        required: true
        schema:
          type: string
      - name: templateId
        in: query
        required: true
        schema:
          type: string
      - name: questionId
        in: query
        required: false
        schema:
          type: integer
      responses:
        200:
          description: L'id della domanda successiva, l'info sullo stato di foglia della odmanda successiva, la frase corretta o inserita dall'utente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'Vas-Response/content'