/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Context;
import io.swagger.client.model.URI;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ContextsApi
 */
@Ignore
public class ContextsApiTest {

    private final ContextsApi api = new ContextsApi();

    
    /**
     * Delete a context
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteContextUsingDELETETest() throws ApiException {
        String id = null;
        api.deleteContextUsingDELETE(id);

        // TODO: test validations
    }
    
    /**
     * Get a context by id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getContextUsingGETTest() throws ApiException {
        String id = null;
        Context response = api.getContextUsingGET(id);

        // TODO: test validations
    }
    
    /**
     * Get the list of available contexts
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getContextsUsingGETTest() throws ApiException {
        Integer page = null;
        Integer size = null;
        String templateId = null;
        List<Context> response = api.getContextsUsingGET(page, size, templateId);

        // TODO: test validations
    }
    
    /**
     * Create a new context
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postContextUsingPOSTTest() throws ApiException {
        Context context = null;
        URI response = api.postContextUsingPOST(context);

        // TODO: test validations
    }
    
    /**
     * Update a context
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void putContextUsingPUTTest() throws ApiException {
        Context context = null;
        String id = null;
        api.putContextUsingPUT(context, id);

        // TODO: test validations
    }
    
}
