/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Content;
import io.swagger.client.model.URI;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ContentsApi
 */
@Ignore
public class ContentsApiTest {

    private final ContentsApi api = new ContentsApi();

    
    /**
     * Delete all contents associated with a resource
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteContentsUsingDELETETest() throws ApiException {
        String id = null;
        api.deleteContentsUsingDELETE(id);

        // TODO: test validations
    }
    
    /**
     * Get a content by id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getContentUsingGETTest() throws ApiException {
        String id = null;
        Content response = api.getContentUsingGET(id);

        // TODO: test validations
    }
    
    /**
     * Create a new content
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postContentUsingPOSTTest() throws ApiException {
        Content content = null;
        String id = null;
        URI response = api.postContentUsingPOST(content, id);

        // TODO: test validations
    }
    
}
