/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Resource;
import io.swagger.client.model.URI;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ResourcesApi
 */
@Ignore
public class ResourcesApiTest {

    private final ResourcesApi api = new ResourcesApi();

    
    /**
     * Delete all resources associated with a context
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteResourcesUsingDELETETest() throws ApiException {
        String id = null;
        api.deleteResourcesUsingDELETE(id);

        // TODO: test validations
    }
    
    /**
     * Create a new resource
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postResourceUsingPOSTTest() throws ApiException {
        String id = null;
        Resource resource = null;
        URI response = api.postResourceUsingPOST(id, resource);

        // TODO: test validations
    }
    
}
