/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Answer;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TemplatesApi
 */
@Ignore
public class TemplatesApiTest {

    private final TemplatesApi api = new TemplatesApi();

    
    /**
     * Retrieve possible answers to a question posed within a context
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAnswersUsingGETTest() throws ApiException {
        String id = null;
        Integer count = null;
        String language = null;
        String question = null;
        List<Answer> response = api.getAnswersUsingGET(id, count, language, question);

        // TODO: test validations
    }
    
    /**
     * Create a lexical index from the contexts of the specified template
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postIndexUsingPOSTTest() throws ApiException {
        String id = null;
        api.postIndexUsingPOST(id);

        // TODO: test validations
    }
    
}
