/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * All details about an Answer in a specific Context.
 */
@ApiModel(description = "All details about an Answer in a specific Context.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-13T11:19:56.034Z")
public class Answer {
  @SerializedName("confidence")
  private Double confidence = null;

  @SerializedName("content")
  private String content = null;

  @SerializedName("reference")
  private String reference = null;

  @SerializedName("uri")
  private String uri = null;

  public Answer confidence(Double confidence) {
    this.confidence = confidence;
    return this;
  }

   /**
   * The confidence value of the answer
   * @return confidence
  **/
  @ApiModelProperty(value = "The confidence value of the answer")
  public Double getConfidence() {
    return confidence;
  }

  public void setConfidence(Double confidence) {
    this.confidence = confidence;
  }

  public Answer content(String content) {
    this.content = content;
    return this;
  }

   /**
   * The content of the answer
   * @return content
  **/
  @ApiModelProperty(value = "The content of the answer")
  public String getContent() {
    return content;
  }

  public void setContent(String content) {
    this.content = content;
  }

  public Answer reference(String reference) {
    this.reference = reference;
    return this;
  }

   /**
   * The reference of the answer
   * @return reference
  **/
  @ApiModelProperty(value = "The reference of the answer")
  public String getReference() {
    return reference;
  }

  public void setReference(String reference) {
    this.reference = reference;
  }

  public Answer uri(String uri) {
    this.uri = uri;
    return this;
  }

   /**
   * The resource where the answer came from
   * @return uri
  **/
  @ApiModelProperty(value = "The resource where the answer came from")
  public String getUri() {
    return uri;
  }

  public void setUri(String uri) {
    this.uri = uri;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Answer answer = (Answer) o;
    return Objects.equals(this.confidence, answer.confidence) &&
        Objects.equals(this.content, answer.content) &&
        Objects.equals(this.reference, answer.reference) &&
        Objects.equals(this.uri, answer.uri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(confidence, content, reference, uri);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Answer {\n");
    
    sb.append("    confidence: ").append(toIndentedString(confidence)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

